[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ESV-web_samhaswon"
version = "0.0.1"
authors = [
  { name="Samuel Howard", email="samuelhoward0725+esv@gmail.com" },
]
description = "A self-hosted webapp connecting to Crossway's ESV API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/samhaswon/ESV-web"