[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Self-hosted Bible"
version = "0.0.1"
authors = [
  { name="Samuel Howard", email="samuelhoward0725+shb@gmail.com" },
]
description = "A self-hosted webapp of various Bible versions including the KJV, ESV, and ASV."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/samhaswon/selfhosted-bible"