name: Docker Image CI

on:
  push:
    branches: [ "main", "rewrite" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v5
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build the image
        run: |
          docker buildx build --push \
            --tag ghcr.io/nmemmert/bible:latest \
            --file Dockerfile.backend \
            --platform linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64,linux/386 .
